language: julia

julia:
  - 1.4
  - nightly

codecov: true

matrix:
  allow_failures:
  - julia: nightly

os:
  - linux
# - osx

notifications:
  email: false

branches:
  only:
  - master
  - /release-.*/
  - /v(\d+)\.(\d+)\.(\d+)/

# https://reflectoring.io/skip-ci-build/
before_install:
  - |
      if ! git diff --name-only $TRAVIS_COMMIT_RANGE | grep -qvE '(.md$)'
      then
        echo "Only docs were updated, not running the CI."
        exit
      fi

after_success:
  - julia -e 'using Pkg; cd(Pkg.dir("ConstantArrays")); Pkg.add("Coverage"); using Coverage; Coveralls.submit(process_folder())';
  - julia -e 'using Pkg; cd(Pkg.dir("ConstantArrays")); Pkg.add("Coverage"); using Coverage; Codecov.submit(process_folder())'
